[package]
name = "lex-lang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = "9.1.2"
clap = { version = "3.1.6", features = [ "derive" ] }

[[bin]]
name = "lex-repl"
path = "src/main.rs"
