style: gitlab
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://gitlab.com/pt-proclub-studio/paas/paas-be
options:
  commits:
     filters:
       Type:
         - feat
         - fix
         - hotfix
         - refactor
         - test
         - misc
         - enhancement
  commit_groups:
     title_maps:
       feat: New Features
       bugfix: Fixes
       hotfix: Critical Fixes
       refactor: Code Improvements
       enhancement: Logic Enhancements
       test: Testing
       misc: Other Improvements
  header:
    pattern: "^(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE

